/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(StateTimer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a7122405d98369cb1716eb8cb5c7a271)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <filerepeater/StateTimer.h>
// pydoc.h is automatically generated in the build directory
#include <StateTimer_pydoc.h>

void bind_StateTimer(py::module& m)
{

    using StateTimer    = ::gr::filerepeater::StateTimer;


    py::class_<StateTimer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<StateTimer>>(m, "StateTimer", D(StateTimer))

        .def(py::init(&StateTimer::make),
           py::arg("delayBeforeStart"),
           py::arg("triggerTime"),
           py::arg("cycleTime"),
           D(StateTimer,make)
        )
        



        ;




}








