/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(TimeOfDay.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d4471aed40aab672a433a2e0bc14e95f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <filerepeater/TimeOfDay.h>
// pydoc.h is automatically generated in the build directory
#include <TimeOfDay_pydoc.h>

void bind_TimeOfDay(py::module& m)
{

    using TimeOfDay    = ::gr::filerepeater::TimeOfDay;


    py::class_<TimeOfDay, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<TimeOfDay>>(m, "TimeOfDay", D(TimeOfDay))

        .def(py::init(&TimeOfDay::make),
           py::arg("hours"),
           py::arg("minutes"),
           py::arg("seconds"),
           py::arg("time_in_sec"),
           D(TimeOfDay,make)
        )
        



        ;




}








